spring:
  profiles:
    include: swagger,mongodb,oauth,security,redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    org.springframework.security: debug

app.running.mode: dev