version: '3.0' #Compose 파일 버전
services: # 서비스 정의 시작. 각 서비스는 별도 컨테이너로 실행
  server:
    image: sapier-back-image:latest #이미지 이름
    container_name: sapier-back-container #컨테이너 이름
    build:
      context: ./backend/sapaier # 컨테이너와 호스트 간의 포트 매핑 설정(외부 연결 가능하게)
      args:
        SERVER_MODE: prod
    ports:
      - 8080:8080 #외부포트 : 내부포트
    environment: # 컨테이너 내부의 환경변수 설정
      - TZ=Asia/Seoul
    networks:
      - sapier_network
  
  #client: # 프론트 서버 정보
  #TODO: 프론트 서버 정보 작성

  nginx: # nginx 정보
    image: nginx:latest
    container_name: nginx
    build:
      context: ./nginx
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - server
      - client
    ports:
      - 80:80
      - 443:443
    networks:
      - sapier_network
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  sapier_network:
    driver: bridge
