/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./components/Request/Body.vue')['default']
    CollectionInfo: typeof import('./components/workspace/CollectionInfo.vue')['default']
    Headers: typeof import('./components/Request/Headers.vue')['default']
    MainInfo: typeof import('./components/main/MainInfo.vue')['default']
    OverviewComponent: typeof import('./components/workspace/OverviewComponent.vue')['default']
    Params: typeof import('./components/Request/Params.vue')['default']
    README: typeof import('./components/README.md')['default']
    RequestInfo: typeof import('./components/Request/RequestInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingComponent: typeof import('./components/workspace/SettingComponent.vue')['default']
    Settings: typeof import('./components/Request/Settings.vue')['default']
    SocialLoginButtonContainer: typeof import('./components/login/SocialLoginButtonContainer.vue')['default']
    SocialLoginContainer: typeof import('./components/login/SocialLoginContainer.vue')['default']
    SocialLoginLogoContainer: typeof import('./components/login/SocialLoginLogoContainer.vue')['default']
    SocialLoginRedirect: typeof import('./components/login/SocialLoginRedirect.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
    UserInfo: typeof import('./components/main/UserInfo.vue')['default']
    WorkSpaceInfo: typeof import('./components/workspace/WorkSpaceInfo.vue')['default']
    WorkspaceList: typeof import('./components/WorkspaceList.vue')['default']
  }
}
